Create Other Clinic schema 🗺️  $ Schema Design📸
gisachris/vet-clinic pull request #6
Opened 2023-07-25 14:43 UTC by gisachris

## IN This PR We present Creating another Clinic schema 🗺️  $ Schema Design📸 
 
Below are some of my implementations as well as going over the project requirements 🤝 .
## Requirements
- use GitFlow 🌊.
- Create new `schema_based_on_diagram.sql` file where you implement the database from the diagram.. ⛱️
- Join tables from many-to-many relationships 🧑‍🤝‍🧑 might not appear in the diagram 🏠 , but you still need them.
- Add the FK indexes🗝️ .
>Schema Diagram
![new_clinic_schema_design](https://github.com/gisachris/vet-clinic/assets/125574259/8ba0b774-a2c7-44b3-b691-2075cf4ddb81)
## Achievements
- use GitFlow 🌊.✅
- Create new `schema_based_on_diagram.sql` file where you implement the database from the diagram.. ⛱️ ✅ 
- Join tables from many-to-many relationships 🧑‍🤝‍🧑 might not appear in the diagram 🏠 , but you still need them. ✅
- Add the FK indexes🗝️ .✅

## Conclusion
**We are looking forward to hearing 👂  from you Our CR in terms of what can be better implemented 👨‍💻  for the project thankyou!. And we look forward to hearing from you soon.**  🙇

2023-07-25 16:56 UTC, Zuhaib042 requested changes
Hi @gisachris  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media.giphy.com/media/YYht2UTV41u1vxHTss/giphy-downsized-large.gif)

## Highlights
✅ Well tried to implement all the requirements


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-25 16:56 UTC, Zuhaib042 commented on schema_based_on_diagram.sql
> +    "id" INTEGER NOT NULL,
- [ ] Kindly consider adding `PRIMARY KEY` in this line as this id should be considered the primary key of this table. I can see that you have Altered this table and did the same thing on line 16 , but I think the concise and better way is to add the primary key inside the table as I mentioned how to do it.

2023-07-25 16:56 UTC, Zuhaib042 commented on schema_based_on_diagram.sql
> +    "patient_id" INTEGER NOT NULL,
- [ ] This is a foreign key. kindly consider to change this line to: 
`patient_id int references patients(id),` to add the foreign key constraint.

2023-07-25 16:56 UTC, Zuhaib042 commented on schema_based_on_diagram.sql
> +    "medical_histories"("patient_id");
- [ ] This line is repeating so kindly consider removing it to make your codebase clean and tidy.

2023-07-25 16:56 UTC, Zuhaib042 commented on schema_based_on_diagram.sql
> +    "invoice_id" INTEGER NOT NULL,
- [ ] This is a foreign key. kindly consider to change this line to: 
`invoice_id int references invoices(id),` to add the foreign key constraint.

2023-07-25 16:56 UTC, Zuhaib042 commented on schema_based_on_diagram.sql
> +    "treatment_id" INTEGER NOT NULL
- [ ] This is a foreign key. kindly consider to change this line to: 
`treatment_id int references treatments(id),` to add the foreign key constraint.

2023-07-25 16:56 UTC, Zuhaib042 commented on schema_based_on_diagram.sql
> +    "treatments_id" INTEGER NOT NULL
- [ ] These two are foreign keys. so you need to reference them here as this is a join table. kindly consider changing these lines to the following:
```
medical_history_id int references medical_histories(id),
treatment_id int references treatments(id),
```

2023-07-25 16:56 UTC, Zuhaib042 commented on schema_based_on_diagram.sql
> +    "medical_treatments"("treatments_id");
- [ ] The foreign key constraints should be in singular name form so consider changing these two ids in brackets to `medical_history_id` and `treatment_id`

2023-07-25 16:56 UTC, Zuhaib042 commented on schema_based_on_diagram.sql
> +    "medical_treatments"("treatments_id");
- [ ] These lines are repeating so consider removing them to make your codebase clean.

2023-07-25 16:56 UTC, Zuhaib042 commented on schema_based_on_diagram.sql
> +    "medical_history_id" INTEGER NOT NULL
- [ ] This is a foreign key. kindly consider to change this line to: 
`medical_history_id int references medical_histories(id),` to add the foreign key constraint.

2023-07-25 16:56 UTC, Zuhaib042 commented on schema_based_on_diagram.sql
> +ALTER TABLE
- [ ] Here you are adding the foreign key constraint where needed but the problem is that we need to add the indexes on all the foreign keys, the index adding should occur after adding the foreign keys, not before them.
If you apply the changes I suggested in the same order, then you would be adding those indexes after adding the foreign keys respectively.

2023-07-25 23:58 UTC, Owusu-Desmond approved these changes
Hi @gisachris and @toyman640 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
📌 No Linters error ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-26 06:50 UTC, merged

2023-07-26 06:51 UTC, gisachris commented
Thanks for the great review @Owusu-Desmond 👏